### ISSUE TITLE
Wrong current salah and remaining time before Fajr 

### ISSUE THREAD

**Issue by rynidja** [azzamsa/islam#6]
Salam,
While testing late night and after midnight I found that:
1- On a new day before fajr, instead of having current salah as Isha it is  Dohr. 
2- Before midnight, the remaining time of fajr is wrong.
[edit: I removed fixes since there is a pull request]

**Comment by azzamsa** [comment]
@rynidja @moanrisy Would you like to try https://github.com/azzamsa/islam/releases/tag/v3.0.0  and report the result?

The issue is covered by the test here
- https://github.com/azzamsa/islam/blob/master/src/salah/times.rs#L528-L531
- https://github.com/azzamsa/islam/blob/master/src/salah/times.rs#L493-498

**Comment by azzamsa** [comment]
@rynidja @Moanrisy I have added more coverage here https://github.com/azzamsa/islam/blob/master/src/salah/times.rs#L548-L566

Pretty sure the mentioned bugs are covered.

Thank you for reporting the bugs! :heart:

**Comment by rynidja** [comment]
I did some testing. 
- Currently it's 2023-09-02 00:05 and next prayer is "FajrTomorrow at 2023-09-03 04:47:26"
- time_remaining seems to work fine

**Comment by azzamsa** [comment]
> * Currently it's 2023-09-02 00:05 and next prayer is "FajrTomorrow at 2023-09-03 04:47:26"

OH, Yes. It should be `Fajr at 2023-09-02 04:47:26`
You can file an issue regarding this.
